import { $, esc, formatTime } from './utils.js';
import { state } from './state.js';
import { duckSay } from './duck.js';
import { getScopeItems } from './scope.js';
import { gatherFormData } from './formData.js';
import { SCORE_THRESHOLDS } from '../../shared/constants.js';

// Shared print helpers
function printHeader(title: string, taskId: string, taskTitle: string): string {
  return `<div class="ps-header"><h1>${title}</h1><p class="ps-meta">${new Date().toLocaleDateString()} · ${esc(taskId || 'No ID')}${taskTitle ? ' · ' + esc(taskTitle) : ''}</p></div><hr>`;
}

function printSection(heading: string, content: string, className?: string): string {
  if (!content.trim()) return '';
  return `<div class="ps-section${className ? ' ' + className : ''}"><h3>${heading}</h3><p>${esc(content)}</p></div>`;
}

function printScopeTable(scope: { text: string; minutes: number }[], showCheckbox: boolean, diffItems?: typeof state.diffItems): string {
  const total = scope.reduce((a, b) => a + b.minutes, 0);
  let h = `<h3>Scope Checklist <span class="ps-dim">(${total} min${total > 60 ? ' / ~' + (total / 60).toFixed(1) + 'h' : ''})</span></h3>`;
  h += `<table class="ps-table"><thead><tr>${showCheckbox ? '<th></th>' : '<th>Status</th>'}<th>Item</th><th>Est.</th></tr></thead><tbody>`;
  scope.forEach((s, i) => {
    const diff = diffItems?.[i];
    const statusIcon = !diff ? '☐' : diff.status === 'done' ? '✓' : '✗';
    const statusClass = !diff ? '' : diff.status === 'done' ? ' class="ps-done"' : ' class="ps-skip"';
    h += `<tr${statusClass}><td>${statusIcon}</td><td>${esc(s.text)}</td><td>${s.minutes}m</td></tr>`;
  });
  h += `</tbody></table>`;
  return h;
}

function printFooter(): string {
  return `<hr><p class="ps-footer">Generated by Task Duck v4 · ${new Date().toLocaleString()}</p>`;
}

export function printPlan(): void {
  const d = gatherFormData(), scope = getScopeItems();
  let h = printHeader('Working Checklist', d.taskId, d.title);

  // Original task (truncated for print)
  if (d.raw) {
    const truncated = d.raw.length > 500 ? d.raw.slice(0, 500) + '...' : d.raw;
    h += `<div class="ps-section ps-original"><h3>Original Task</h3><p>${esc(truncated)}</p></div>`;
  }

  h += printSection('What\'s Being Asked', d.ask);
  h += printSection('Deliverable', d.deliverable);
  h += printSection('Definition of Done', d.dod);
  if (d.notAsked) h += `<div class="ps-section ps-exclude"><h3>NOT In Scope</h3><p>${esc(d.notAsked)}</p></div>`;

  // Verification status
  if (state.lastVerdict) {
    const verdictLabel = state.lastVerdict === 'match' ? '✓ Match' : state.lastVerdict === 'drift' ? '⚠ Drift' : '✗ ' + state.lastVerdict.replace('_', ' ');
    const lastEntry = state.verificationHistory[state.verificationHistory.length - 1];
    h += `<div class="ps-section ps-verify"><h3>AI Verification</h3><p><strong>${verdictLabel}</strong>${lastEntry ? ' (' + lastEntry.confidence + '% confidence)' : ''}${lastEntry?.summary ? ' — ' + esc(lastEntry.summary) : ''}</p></div>`;
  }

  if (d.storyPoints) h += `<div class="ps-section"><h3>Story Points</h3><p>${esc(d.storyPoints)}</p></div>`;

  h += printScopeTable(scope, true);
  h += printSection('Approach', d.approach);

  // Reviewer section
  if (d.peerWho) {
    let reviewerContent = esc(d.peerWho);
    if (d.peerSurprise) reviewerContent += `<br><span class="ps-dim">Would surprise them:</span> ${esc(d.peerSurprise)}`;
    h += `<div class="ps-section"><h3>Reviewer</h3><p>${reviewerContent}</p></div>`;
  }

  if (d.parkingLot) h += `<div class="ps-section ps-parking"><h3>Parking Lot (NOT doing now)</h3><p>${esc(d.parkingLot)}</p></div>`;

  if (state.lastVerdict && state.lastVerdict !== 'match' && d.driftReason) {
    h += `<div class="ps-section ps-exclude"><h3>Known Drift</h3><p>${esc(d.driftReason)}</p></div>`;
  }

  h += printFooter();
  $('printSheet').innerHTML = h;
  window.print();
}

export function printFinal(): void {
  const d = gatherFormData(), scope = getScopeItems();
  const planned = state.diffItems.length;
  const done = state.diffItems.filter(x => x.status === 'done').length;
  const skipped = state.diffItems.filter(x => x.status === 'skipped').length;
  const extraCount = state.extras.length;
  const amendCount = state.amendments.length;
  const deduction = extraCount * SCORE_THRESHOLDS.extraPenalty;
  const pct = planned > 0 ? Math.round((done / planned) * 100) : 0;
  const score = Math.max(0, pct - deduction);

  let h = printHeader('Final Report', d.taskId, d.title);

  // Summary stats box
  h += `<div class="ps-stats-box"><div class="ps-stat"><span class="ps-stat-num">${score}%</span><span class="ps-stat-lbl">Accuracy</span></div><div class="ps-stat"><span class="ps-stat-num">${done}/${planned}</span><span class="ps-stat-lbl">Completed</span></div><div class="ps-stat"><span class="ps-stat-num">${extraCount}</span><span class="ps-stat-lbl">Extras</span></div><div class="ps-stat"><span class="ps-stat-num">${amendCount}</span><span class="ps-stat-lbl">Amended</span></div>${state.workTimerSeconds > 0 ? `<div class="ps-stat"><span class="ps-stat-num">${formatTime(state.workTimerSeconds)}</span><span class="ps-stat-lbl">Work Time</span></div>` : ''}</div>`;

  if (d.raw) {
    const truncated = d.raw.length > 400 ? d.raw.slice(0, 400) + '...' : d.raw;
    h += `<div class="ps-section ps-original"><h3>Original Task</h3><p>${esc(truncated)}</p></div>`;
  }
  h += printSection('Understanding', d.ask);
  h += printSection('Deliverable', d.deliverable);
  h += printSection('Definition of Done', d.dod);
  if (d.notAsked) h += `<div class="ps-section ps-exclude"><h3>NOT In Scope</h3><p>${esc(d.notAsked)}</p></div>`;

  // Scope table with actual status
  h += printScopeTable(scope, false, state.diffItems);

  // Extras & amendments
  if (state.extras.length) {
    h += `<div class="ps-section ps-exclude"><h3>Unplanned Extras (${extraCount})</h3>`;
    state.extras.forEach(e => { h += `<p>⚠ ${esc(e.text)}</p>`; });
    h += `</div>`;
  }
  if (state.amendments.length) {
    h += `<div class="ps-section"><h3>Scope Amendments (${amendCount})</h3>`;
    state.amendments.forEach(a => { h += `<p>${esc(a.text)}</p>`; });
    h += `</div>`;
  }

  // Skipped items callout
  if (skipped > 0) {
    h += `<div class="ps-section ps-exclude"><h3>Skipped Items (${skipped})</h3>`;
    state.diffItems.filter(x => x.status === 'skipped').forEach(x => { h += `<p>✗ ${esc(x.text)}</p>`; });
    h += `</div>`;
  }

  h += printSection('Approach', d.approach);
  if (d.peerWho) h += printSection('Reviewer', d.peerWho);
  if (d.parkingLot) h += `<div class="ps-section ps-parking"><h3>Parking Lot (deferred)</h3><p>${esc(d.parkingLot)}</p></div>`;

  if (state.lastVerdict && state.lastVerdict !== 'match' && d.driftReason) {
    h += `<div class="ps-section ps-exclude"><h3>Known Drift</h3><p>${esc(d.driftReason)}</p></div>`;
  }

  h += printFooter();
  $('printSheet').innerHTML = h;
  window.print();
}

export function exportMarkdown(): void {
  const d = gatherFormData(), scope = getScopeItems();
  let md = `## 🦆 Task Duck — ${d.taskId} ${d.title}\n\n**Date:** ${new Date().toLocaleDateString()}\n\n`;
  md += `### What's Being Asked\n${d.ask}\n\n### Deliverable\n${d.deliverable}\n\n### Definition of Done\n${d.dod}\n\n### NOT In Scope\n${d.notAsked}\n\n`;
  if (d.storyPoints) md += `**Story Points:** ${d.storyPoints}\n\n`;
  md += `### Scope\n${scope.map(s => `- [ ] ${s.text} (${s.minutes}m)`).join('\n')}\n\n`;
  if (d.approach) md += `### Approach\n${d.approach}\n\n`;
  if (d.parkingLot) md += `### Parking Lot\n${d.parkingLot}\n\n`;
  ($('mdContent') as HTMLTextAreaElement).value = md;
  $('mdOverlay').classList.add('show');
}

export function closeMd(): void {
  $('mdOverlay').classList.remove('show');
}

export function copyMd(): void {
  navigator.clipboard.writeText(($('mdContent') as HTMLTextAreaElement).value);
  duckSay("Markdown copied!");
}

export function copyShipSummary(): void {
  const d = gatherFormData(), scope = getScopeItems();
  const planned = state.diffItems.length;
  const done = state.diffItems.filter(x => x.status === 'done').length;
  const skipped = state.diffItems.filter(x => x.status === 'skipped').length;
  const extraCount = state.extras.length;
  const amendCount = state.amendments.length;
  const score = $('accScore').textContent || '0%';

  let md = `## Task Duck — Ship Summary\n\n`;
  md += `**Task:** ${d.taskId} ${d.title}\n`;
  md += `**Date:** ${new Date().toLocaleDateString()}\n`;
  md += `**Accuracy:** ${score}\n\n`;
  md += `### Scope\n`;
  scope.forEach(s => { md += `- ${s.text} (${s.minutes}m)\n`; });
  md += `\n### Diff\n`;
  md += `- Done: ${done}/${planned}\n`;
  md += `- Skipped: ${skipped}\n`;
  md += `- Extras: ${extraCount}\n`;
  md += `- Amendments: ${amendCount}\n`;
  if (state.extras.length) {
    md += `\n### Extras\n`;
    state.extras.forEach(e => { md += `- ${e.text}\n`; });
  }
  if (state.amendments.length) {
    md += `\n### Amendments\n`;
    state.amendments.forEach(a => { md += `- ${a.text}\n`; });
  }
  md += `\n---\n*Generated by Task Duck v4*\n`;

  navigator.clipboard.writeText(md).then(() => {
    duckSay("Summary copied to clipboard!");
    const toast = $('toastCopied');
    toast.classList.add('show');
    setTimeout(() => toast.classList.remove('show'), 2000);
  }).catch(() => {
    duckSay("Copy failed — try manually.");
  });
}
