import { $, esc } from './utils.js';
import { state } from './state.js';
import { duckSay } from './duck.js';
import { getScopeItems } from './scope.js';

function gatherData() {
  return {
    taskId: ($('taskIdField') as HTMLInputElement).value,
    title: ($('taskTitleField') as HTMLInputElement).value,
    raw: ($('rawTaskField') as HTMLTextAreaElement).value,
    ask: ($('askField') as HTMLTextAreaElement).value,
    deliverable: ($('deliverableField') as HTMLTextAreaElement).value,
    dod: ($('dodField') as HTMLTextAreaElement).value,
    notAsked: ($('notAskedField') as HTMLTextAreaElement).value,
    approach: ($('approachField') as HTMLTextAreaElement).value,
    peerWho: ($('peerWho') as HTMLTextAreaElement).value,
    peerSurprise: ($('peerSurprise') as HTMLTextAreaElement).value,
    parkingLot: ($('parkingLot') as HTMLTextAreaElement).value,
    storyPoints: ($('storyPointsField') as HTMLInputElement).value,
  };
}

export function printPlan(): void {
  const scope = getScopeItems();
  const total = scope.reduce((a, b) => a + b.minutes, 0);
  let h = `<h1 style="font-size:16pt;margin-bottom:2pt">🦆 Task Duck — Working Checklist</h1>`;
  h += `<p style="font-size:9pt;color:#666;margin-bottom:10pt">${new Date().toLocaleDateString()} · ${($('taskIdField') as HTMLInputElement).value || 'No ID'} · ${($('taskTitleField') as HTMLInputElement).value || ''}</p><hr style="margin:8pt 0">`;
  h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">What's Being Asked</h3><p style="font-size:10pt">${esc(($('askField') as HTMLTextAreaElement).value)}</p>`;
  h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">Deliverable</h3><p style="font-size:10pt">${esc(($('deliverableField') as HTMLTextAreaElement).value)}</p>`;
  h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">Definition of Done</h3><p style="font-size:10pt">${esc(($('dodField') as HTMLTextAreaElement).value)}</p>`;
  h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">NOT In Scope</h3><p style="font-size:10pt;color:#c00">${esc(($('notAskedField') as HTMLTextAreaElement).value)}</p><hr style="margin:8pt 0">`;
  const sp = ($('storyPointsField') as HTMLInputElement).value;
  if (sp) h += `<p style="font-size:10pt;font-weight:600;color:#666;margin:4pt 0">Story Points: ${esc(sp)}</p>`;
  h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">Scope Checklist (${total} min)</h3>`;
  scope.forEach(s => { h += `<div style="margin:4pt 0;font-size:10pt">☐ ${esc(s.text)} <span style="color:#888">(${s.minutes}m)</span></div>`; });
  const approach = ($('approachField') as HTMLTextAreaElement).value;
  if (approach) h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">Approach</h3><p style="font-size:10pt">${esc(approach)}</p>`;
  const peerWho = ($('peerWho') as HTMLTextAreaElement).value;
  if (peerWho) h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">Reviewer</h3><p style="font-size:10pt">${esc(peerWho)}</p>`;
  const parkingLot = ($('parkingLot') as HTMLTextAreaElement).value;
  if (parkingLot) h += `<h3 style="font-size:11pt;margin:6pt 0 3pt">Parking Lot (NOT doing now)</h3><p style="font-size:10pt;color:#888">${esc(parkingLot)}</p>`;
  if (state.lastVerdict && state.lastVerdict !== 'match' && ($('driftReason') as HTMLInputElement).value) {
    h += `<h3 style="font-size:11pt;margin:6pt 0 3pt;color:#c00">⚠ Known Drift</h3><p style="font-size:10pt">${esc(($('driftReason') as HTMLInputElement).value)}</p>`;
  }
  h += `<hr style="margin:10pt 0"><p style="font-size:8pt;color:#999">Generated by Task Duck v4 · ${new Date().toLocaleString()}</p>`;
  $('printSheet').innerHTML = h;
  window.print();
}

export function printFinal(): void {
  let h = `<h1 style="font-size:16pt;margin-bottom:2pt">🦆 Task Duck — Final Report</h1>`;
  h += `<p style="font-size:9pt;color:#666;margin-bottom:10pt">${new Date().toLocaleDateString()} · ${($('taskIdField') as HTMLInputElement).value || ''} · ${($('taskTitleField') as HTMLInputElement).value || ''}</p><hr>`;
  h += `<h3 style="margin:6pt 0 3pt">Understanding</h3><p style="font-size:10pt">${esc(($('askField') as HTMLTextAreaElement).value)}</p>`;
  h += `<h3 style="margin:6pt 0 3pt">Definition of Done</h3><p style="font-size:10pt">${esc(($('dodField') as HTMLTextAreaElement).value)}</p>`;
  h += `<h3 style="margin:6pt 0 3pt">Accuracy: ${$('accScore').textContent}</h3><p style="font-size:10pt">${$('accDetail').textContent}</p>`;
  h += `<h3 style="margin:6pt 0 3pt">Diff</h3>`;
  state.diffItems.forEach(d => { h += `<div style="font-size:10pt;margin:2pt 0">${d.status === 'done' ? '✅' : '❌'} ${esc(d.text)}</div>`; });
  if (state.extras.length) { h += `<h4 style="margin:4pt 0;color:#c00">Extras</h4>`; state.extras.forEach(e => { h += `<div style="font-size:10pt;margin:2pt 0">⚠ ${esc(e.text)}</div>`; }); }
  if (state.amendments.length) { h += `<h4 style="margin:4pt 0;color:#36f">Amendments</h4>`; state.amendments.forEach(a => { h += `<div style="font-size:10pt;margin:2pt 0">📋 ${esc(a.text)}</div>`; }); }
  h += `<hr><p style="font-size:8pt;color:#999">Task Duck v4 · ${new Date().toLocaleString()}</p>`;
  $('printSheet').innerHTML = h;
  window.print();
}

export function exportMarkdown(): void {
  const d = gatherData(), scope = getScopeItems();
  let md = `## 🦆 Task Duck — ${d.taskId} ${d.title}\n\n**Date:** ${new Date().toLocaleDateString()}\n\n`;
  md += `### What's Being Asked\n${d.ask}\n\n### Deliverable\n${d.deliverable}\n\n### Definition of Done\n${d.dod}\n\n### NOT In Scope\n${d.notAsked}\n\n`;
  if (d.storyPoints) md += `**Story Points:** ${d.storyPoints}\n\n`;
  md += `### Scope\n${scope.map(s => `- [ ] ${s.text} (${s.minutes}m)`).join('\n')}\n\n`;
  if (d.approach) md += `### Approach\n${d.approach}\n\n`;
  if (d.parkingLot) md += `### Parking Lot\n${d.parkingLot}\n\n`;
  ($('mdContent') as HTMLTextAreaElement).value = md;
  $('mdOverlay').classList.add('show');
}

export function closeMd(): void {
  $('mdOverlay').classList.remove('show');
}

export function copyMd(): void {
  navigator.clipboard.writeText(($('mdContent') as HTMLTextAreaElement).value);
  duckSay("Markdown copied!");
}
